# Generated by Django 5.1.3 on 2024-12-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='image',
            field=models.ImageField(default='projects/default project.png', upload_to='projects/subtask/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='projects/default project.png', upload_to='projects/task/'),
        ),
    ]
