# Generated by Django 5.1.3 on 2024-12-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
